### PR TITLE
Conditional manage repository

### PR DESCRIPTION
**Pull request by iszak**
This is a fork of the work done in this pull request https://github.com/puppetlabs/puppetlabs-logentries/pull/4 with a rebase and squash of the commits.

This also adds the option to not manage the repository.

### CODE REVIEW

**Comment by tphoney** [comment]
Thanks for squashing #4  and adding more cleanup. There are a few comments i have:
+ Can you please squash your additional commits in this PR.
+ There are other additional changes you have made in your branch, that may be backwards incompatible init.pp (they are not in this PR). Just as a warning

Cheers,
TP

**Comment by iszak** [comment]
@tphoney which changes specifically are you talking about that may break backwards compatibility?

**Comment by tphoney** [comment]
class { 'logentries':
-      account_key => 'key',
+      le_account_key => 'key',
     }
This would result in breaking existing installations. Or am i missing something ?

**Comment by iszak** [comment]
@tphoney the prefixing of `le_xxx` is from the previous ticket ( https://github.com/puppetlabs/puppetlabs-logentries/pull/4/files ) but yes it will break things, as I understood it, it was required because `hostname` is a reserved/top scope variable. I can keep it if need be.

**Comment by tphoney** [comment]
le_account_key should just be account_key, it was not part of #4.

**Comment by iszak** [comment]
@tphoney I can't see "le_account_key" as part of my PR?

**Comment by tphoney** [comment]
To be clear it is not part of this PR it is part of commit dd79487a9474c9558ce24c523d2b8a49419b6e4a from iszak:patch-1. 
Sorry for the confusion.

**Comment by iszak** [comment]
@tphoney ah yes this is part of a larger refactor (params.pp, install.pp, service.pp, le init vs le register) which I plan to follow up after this PR, I figured a lot will be changed so a breakage is probably more acceptable, but if we can keep backwards compatibility then I'm happy to try it.

**Pull request merged**
